# Generated by Django 4.0.5 on 2022-06-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_city_alter_dispositivo_propietario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='nombre',
            new_name='ubicacion',
        ),
        migrations.RenameField(
            model_name='perrito',
            old_name='nombre',
            new_name='nombre_perro',
        ),
    ]
