# Generated by Django 4.0.5 on 2022-06-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_usuario_alter_perrito_dueño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='nombre_usuarios',
        ),
    ]
