# Generated by Django 4.0.5 on 2022-06-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_rename_nombre_usuario_usuario_nombre_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perrito',
            old_name='nombre_perro',
            new_name='nombre_perrito',
        ),
    ]
