# Generated by Django 4.0.3 on 2022-06-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_rename_nombre_perro_perrito_nombre_perrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='Api.usuario'),
        ),
    ]
