# Generated by Django 4.0.3 on 2022-06-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_alter_dispositivo_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='mensaje',
            field=models.CharField(default='JAMPIOIIIIII', max_length=50),
        ),
    ]
