# Generated by Django 4.0.3 on 2022-06-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_horario_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='foto',
            field=models.CharField(max_length=50),
        ),
    ]
