# Generated by Django 4.0.3 on 2022-06-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_alter_perrito_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='propietario',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='ubicacion',
            new_name='ubication',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='Dispo',
            new_name='Dispositivo',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='hora',
            new_name='hour',
        ),
        migrations.RenameField(
            model_name='perrito',
            old_name='edad',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='perrito',
            old_name='nombre_perrito',
            new_name='dog_name',
        ),
        migrations.RenameField(
            model_name='perrito',
            old_name='dueño',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='perrito',
            name='raza',
        ),
        migrations.RemoveField(
            model_name='perrito',
            name='ult_alimentacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_usuarios',
        ),
        migrations.AddField(
            model_name='horario',
            name='last_feed',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='horario',
            name='cantidad_comida',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
