# Generated by Django 4.0.3 on 2022-07-01 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0011_rename_ubication_dispositivo_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros', to=settings.AUTH_USER_MODEL),
        ),
    ]
