# Generated by Django 4.0.3 on 2022-07-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_alter_dispositivo_propietario_alter_perrito_dueño'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='imagen',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='perrito',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='perrito',
            name='ult_alimentacion',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='url_conexion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='ubicacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='horario',
            name='cantidad_comida',
            field=models.CharField(choices=[('Poco', 'Poco'), ('Masomenos', 'Masomenos'), ('Mucho', 'Mucho')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='raza',
            field=models.CharField(max_length=50),
        ),
    ]
