# Generated by Django 4.0.3 on 2022-07-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_perrito_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='url_conexion',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='cantidad_comida',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='perrito',
            old_name='nombre_perrito',
            new_name='nombre',
        ),
    ]
