# Generated by Django 4.0.3 on 2022-07-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_rename_url_conexion_dispositivo_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='url',
            new_name='url_conexion',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='cantidad',
            new_name='cantidad_comida',
        ),
        migrations.RenameField(
            model_name='perrito',
            old_name='nombre',
            new_name='nombre_perrito',
        ),
    ]
