# Generated by Django 4.0.3 on 2022-07-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_rename_url_dispositivo_url_conexion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='foto',
            field=models.CharField(max_length=200),
        ),
    ]
